# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f672bcbebe8fde87740c2c0a44ecec9cba11ed4104d763845d96b29a6414b5b54e5ddef9dcf2549aa4dcd17d9902fa68a6c3af48be5e2103ee5dcd658d9ef1b4

test:
  secret_key_base: c0a932f717528ad1780470d82f174099ce82f4b6ec6ff2c6c9325e5072a3adc6c861df5afaa5348b4d69e7cf1367369c86162a703c5810dc88aa1423deac7f00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
